name: Build and Push Django Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 3. Generate image tag (timestamp)
      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t hafidzalasqalani/webai:latest -t hafidzalasqalani/webai:${IMAGE_TAG} .

      # 5. Push Docker image
      - name: Push Docker image
        run: |
          docker push hafidzalasqalani/webai:latest
          docker push hafidzalasqalani/webai:${IMAGE_TAG}
